Cargo.toml
src/connectors/fname/mod.rs
src/connectors/mod.rs
src/main.rs

Initial version of code to fetch fnames and store them in memory (for now).
This also uses the `tracing` logger and enables json output.
When running, you can see lines like:
```
{"timestamp":"2024-11-02T01:22:35.272756Z","level":"DEBUG","fields":{"message":"fetching transfers","url":"https://fnames.farcaster.xyz/transfers?from_id=685400"},"target":"snapchain::connectors::fname"}
{"timestamp":"2024-11-02T01:22:35.751982Z","level":"INFO","fields":{"message":"found new transfers","count":100,"position":685400},"target":"snapchain::connectors::fname"}
{"timestamp":"2024-11-02T01:22:35.752016Z","level":"DEBUG","fields":{"message":"fetching transfers","url":"https://fnames.farcaster.xyz/transfers?from_id=685500"},"target":"snapchain::connectors::fname"} …
```

v0: fname fetcher

---

Cargo.toml
config/sample.toml
src/cfg.rs
src/connectors/fname/mod.rs
src/lib.rs
src/main.rs
src/tests/cfg_test.rs
src/tests/mod.rs

Configuration system.
This allows configurations in TOML files:
```
log_format = "json"
id = 1
[fnames]
disable = false
stop_at = 9999999999
start_from = 0
url = "https://fnames.farcaster.xyz/transfers"
```
You specify the file with e.g. `cargo run -- --config-path node1.toml`
Currently possible to run without specifying any config file, but you'd have to pass the node id, e.g. `cargo run -- --id 1`
Environment variables take precedence over config files.
```
SNAPCHAIN_ID=1  cargo run --
````
or
```
SNAPCHAIN_FNAMES__URL=http://localhost:8000/transfers cargo run -- --id 1
```
Note the use of both single and double underscores to reference nested fields.
I don't love how much manual effort is required to add each command line flag (see the lengthy comment in code), but I couldn't see an …

config system

---

.gitignore
README.md
src/bin/setup.rs
src/cfg.rs
src/consensus/consensus.rs
src/consensus/timers.rs
src/core/types.rs
src/main.rs
src/network/gossip.rs
tests/consensus_test.rs

Run the following to generate config files for 4 nodes
```
cargo run --bin setup
```
This lets you have persistent private keys for your nodes.
When starting with an `id` argument, we'll automatically load a config file under `nodes/{id}` if present
Also added missing consensus messages via gossip. Block production works over gossip now.

Read keys from config files and write missing consensus gossip messages

---

src/consensus/consensus.rs
src/core/types.rs
src/main.rs
src/network/gossip.rs
src/proto/blocks.proto
tests/consensus_test.rs

Add shard and block proposers that can independently propose values.
They are not wired together yet, so Blocks don't yet have ShardChunks populated.

Sharded consensus

---

src/bin/setup.rs
src/cfg.rs
src/consensus/consensus.rs
src/core/types.rs
src/main.rs
src/network/gossip.rs
src/proto/blocks.proto

We need to be able to reach peers via rpc for block sync, so add the rpc address to the broadcasted info about each validator.

add rpc address to RegisterValidator

---

src/bin/setup.rs
src/bin/submit-message.rs
src/connectors/fname/mod.rs
src/consensus/consensus.rs
src/core/types.rs
src/lib.rs
src/main.rs
src/network/gossip.rs
src/network/server.rs
src/node/mod.rs
src/node/snapchain_node.rs
src/proto/blocks.proto
tests/consensus_test.rs

Creates multiple shard validators within a single snapchain node. By default one for the block and one for a single shard. But can support multiple shards. 
Gossip/Consensus messages are forwarded to the appropriate shard validator. 
Blocks are only produced if shard chunks are confirmed for the same height.

Sharded Block Production

---

build.rs
src/consensus/consensus.rs
src/consensus/timers.rs
src/core/types.rs
src/node/snapchain_node.rs
tests/consensus_test.rs

Creating a node with 2 shards wasn't working because the block proposer was using the length of the `shard_ids` string as the num_nodes instead of the length of the vector.
Reduced duplication in tests and made it easier to spin up a network of nodes.
Remove re-implementation of Height and used Height prost.

Fix multiple shards and clean up tests

---

src/bin/setup.rs
src/cfg.rs
src/consensus/proposer.rs
src/consensus/validator.rs
src/main.rs
src/utils/cli.rs

Allows starting nodes with `--clear-db` that will delete all existing local state to make it easier to test

Add cli argument to optionally clear the db

---

src/storage/store/engine.rs
src/storage/store/shard.rs
src/storage/trie/commit_rollback_tests.rs
src/storage/trie/merkle_trie.rs
src/storage/trie/mod.rs

This is a little messy but it does a few things:
- hashes of messages are added to the trie during propose, then rolled back
- hashes are again added during commit, and we check that the hashes match before committing or (for not at least) panicking
Still a lot to do but POC somewhat validated.

trie commit and rollback v0

---

docker-compose.yml
src/bin/setup.rs

Each container has its own file namespace, so set the RocksDB location to the same value for each container so it's easier for us to define mounts.

Update default rocksdb_dir to be container-friendly

---

build.rs
src/lib.rs
src/network/server.rs
src/node/snapchain_node.rs
src/proto/blocks.proto
src/proto/hub_event.proto
src/proto/onchain_event.proto
src/storage/constants.rs
src/storage/store/account/mod.rs
src/storage/store/account/onchain_event_store.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs
tests/consensus_test.rs

Start storing onchain events. Onchain events still aren't plumbed through consensus, but we can manually feed them to the engine and test behavior.

store on chain events from the engine

---

src/lib.rs

The `message` package was renamed to `msg`. Rename in `lib.rs` for the proto build.

fix message proto package name

---

README.md

Because this doesn't stop the LLM spam and it adds friction for legitimate contributors.

Remove external PRs note

---

src/network/gossip.rs

There are issues connecting to bootstrap peers. Add more logging to understand which bootstrap peer we're failing on.

add logging for processing a bootstrap peer

---

src/network/gossip.rs

The config introduced a whitespace for bootstrap peers and it wouldn't parse. Change the parsing so that we can tolerate some whitespace.

strip whitespace from bootstrap peers

---

Cargo.lock
Cargo.toml
src/consensus/consensus.rs
src/consensus/proposer.rs
src/core/message.rs
src/network/server.rs
src/node/snapchain_node.rs
src/proto/blocks.proto
src/storage/store/account/store.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs
tests/consensus_test.rs

Reflect store operations in the trie and refactor engine to create multiple transactions.

Support deletes

---

src/consensus/proposer.rs
src/main.rs
src/node/snapchain_node.rs
tests/consensus_test.rs

Nodes were halting as the block channel filled up. The fix is to not initialize the tx channel given we never read from the rx. Tested with a local 3 node setup.

remove block channel that we don't read from

---

src/consensus/proposer.rs
src/core/types.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs
src/storage/store/shard.rs
src/storage/trie/commit_rollback_tests.rs
src/storage/trie/merkle_trie.rs
src/storage/trie/merkle_trie_tests.rs
src/utils/cli.rs
src/utils/factory.rs
src/utils/mod.rs

Insert messages into the trie using the correct prefixes so we now have account specific state roots.
Also added more tests, and fixed reloading an empty trie

Account state roots

---

src/bin/collect_stats.rs
src/consensus/proposer.rs
src/network/server.rs
src/proto/rpc.proto
src/utils/cli.rs

In the follow blocks script, we end up getting all the blocks from the beginning up to the latest when what we really wanna do is see the blocks minted starting from the time when we run the script. Add an optional start timestamp parameter to the `GetBlocks` request to support this.

add an optional start timestamp to the rpc to get blocks

---

src/main.rs
src/network/server.rs
src/network/server_tests.rs
src/node/snapchain_node.rs
src/storage/store/account/cast_store.rs
src/storage/store/account/onchain_event_store.rs
src/storage/store/account/store.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs
src/storage/store/shard.rs
src/storage/trie/merkle_trie.rs
tests/consensus_test.rs

Add support for reading from the db in the event stream. 
Along with this, I refactored the way we deal with stores and channels in the engine. We started creating a bunch of ad-hoc maps to feed data in the engine to the rpc server. Refactored this to pull out all the stores/channel senders together.

read persisted events from db for event stream

---

Dockerfile
src/bin/perftest.rs
src/bin/statsd_printer.rs
src/bin/submit_message.rs
src/main.rs
src/network/server.rs
src/network/server_tests.rs
src/storage/store/engine.rs
src/utils/statsd_wrapper.rs
tests/consensus_test.rs

This PR does a few things:
- rename `collect_stats` to `pertest`
- add a panic handler to perftest so it exits if any thread panics
- add a `statsd_printer` script that can listen to UDP 8125 to print metric names for debugging
- add stats for grpc submit_message
- add and refactor engine stats
- a few misc fixes
New metrics come out with keys looking like these:
```
c  snapchain1.rpc.submit_message.success
c  snapchain1.shard1.engine.commit.invoked
c  snapchain1.shard1.engine.commit.system_messages
c  snapchain1.shard1.engine.commit.transactions
c  snapchain1.shard1.engine.commit.user_messages
c  snapchain1.shard1.engine.prepare_proposal.recv_messages
c  snapchain1.shard1.engine.prepare_proposal.system_messages
c  snapchain1.shard1.engine.prepare_proposal.transactions
c …
```

fixes for perf test

---

src/storage/store/account/link_store.rs
src/storage/store/account/mod.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs
src/utils/factory.rs

Support link messages in the engine.

migrate link store

---

src/bin/perftest.rs
src/consensus/proposer.rs
src/network/server.rs
src/proto/rpc.proto
src/utils/cli.rs

This reverts commit 6b5f0a21086e8489e0b5651e8c754ae474f0268c.

Revert "add an optional start timestamp to the rpc to get blocks (#89)"

---

src/consensus/proposer.rs
src/network/server.rs
src/proto/rpc.proto
src/storage/store/block.rs
src/utils/cli.rs
tests/consensus_test.rs

Implement get blocks as a streaming rpc to fix some of the usability issues.

implement get blocks as streaming rpc

---

src/bin/perftest.rs
src/main.rs
src/network/admin_server.rs
src/network/server.rs
src/proto/admin_rpc.proto
src/utils/cli.rs

We need to have a storage allocation for an fid before we can accept a message for it. Add the ability to submit an onchain event via rpc to unblock successfully submitting messages via rpc.

add endpoint for submitting onchain events via rpc

---

src/utils/cli.rs

We can't allocate legacy storage units and new storage units to the same user-- fix the mock storage unit allocation to not do this.

fix mock storage unit allocation for perftest

---

src/bin/submit_message.rs
src/consensus/proposer.rs
src/main.rs
src/network/server.rs
src/network/server_tests.rs
src/perf/perftest.rs
src/proto/rpc.proto
src/utils/cli.rs
tests/consensus_test.rs

The service name needs to be the same as it is in the existing hubs for compatibility.

rename SnapchainService to HubService

---

src/network/server.rs
src/proto/rpc.proto

We'll use this endpoint for submitting existing hub messages to snapchain nodes. This avoids us needing to remove qualified module names.

add submitLegacyMessage endpoint

---

build.rs
src/bin/submit_message.rs
src/consensus/proposer.rs
src/lib.rs
src/main.rs
src/network/server.rs
src/network/server_tests.rs
src/perf/perftest.rs
src/proto/legacy_rpc.proto
src/proto/rpc.proto
src/utils/cli.rs
tests/consensus_test.rs

Putting `submitLegacyMessage` in the existing rpc service doesn't work due to namespacing issues-- the service is in the "rpc" namespace. Move this endpoint into a new service at the root namespace that exactly matches the proto structure of the parallel hub rpc. 
Future compatible rpcs should go there too.

create separate service at root namespace for hub compatible rpcs

---

src/storage/store/account/user_data_store.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs
src/storage/store/test_helper.rs
src/utils/factory.rs

We need to revoke an existing username when the fname is transferred to a different fid

Revoke username when fname is transferred

---

src/network/server.rs
src/network/server_tests.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs
src/storage/store/stores.rs

Implement message simulation to provide feedback to clients immediately if the message is invalid. This does not guarantee the message will eventually be merged (could become invalid while in the mempool)

Simulate merging a message on submit to provide errors early

---

src/storage/store/account/onchain_event_store.rs

Return error for duplicate onchain events rather than successfully merging. This mirrors existing hub behavior.

don't merge duplicate onchain events

---

src/network/server.rs
src/proto/rpc.proto

It's useful to have visibility into which message types have differing counts for reach fid to validate the migration.
```
❯ grpcurl -plaintext -proto src/proto/rpc.proto -import-path src/proto -d '{"fid": 503}' 127.0.0.1:3383 HubService/GetInfoByFid
{
"numMessagesByMessageType": {
"1": "100",
"2": "0",
"3": "386",
"4": "17",
"5": "97",
"6": "0",
"7": "0",
"8": "0",
"11": "0",
"12": "0",
"13": "0",
"14": "0"
}
}
```

add endpoint for message counts by fid

---

src/network/server.rs
src/proto/rpc.proto

Add overall per-fid message count to the `GetInfoByFid` rpc response. This is useful for understanding message count discrepancies in onchain events. 
```
❯ grpcurl -plaintext -proto src/proto/rpc.proto -import-path src/proto -d '{"fid": 522}' 127.0.0.1:3383 HubService/GetInfoByFid
{
"numMessages": "70",
"numMessagesByMessageType": {
"1": "14",
"2": "0",
"3": "0",
"4": "0",
"5": "49",
"6": "0",
"7": "0",
"8": "0",
"11": "3",
"12": "0",
"13": "0",
"14": "0"
}
}
```

add overall fid message count to stats

---

src/storage/trie/merkle_trie.rs
src/storage/trie/merkle_trie_tests.rs

Sometimes there are multiple signers created in the same transaction. We need log index to differentiate them.

add log index to onchain event trie key

---

src/consensus/proposer.rs
src/node/snapchain_node.rs

Will help determine if this is where we are leaking memory

Emit stats for uncommitted data in the proposers

---

src/consensus/proposer.rs

Remove all old heights from the pending shard chunks hashmap once we decide on a height. We're leaking memory because this keeps growing. But we also need to understand why this is happening in the first place.

Fix proposer memory leak

---

src/core/message.rs
src/core/types.rs
src/mempool/routing.rs
src/network/admin_server.rs
src/network/server.rs
src/network/server_tests.rs
src/perf/gen_multi.rs
src/perf/gen_single.rs
src/storage/store/account/cast_store.rs
src/storage/store/account/link_store.rs
src/storage/store/account/message.rs
src/storage/store/account/name_registry_events.rs
src/storage/store/account/onchain_event_store.rs
src/storage/store/account/reaction_store.rs
src/storage/store/account/store.rs
src/storage/store/account/user_data_store.rs
src/storage/store/account/username_proof_store.rs
src/storage/store/account/verification_store.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs
src/storage/store/stores.rs
src/storage/store/test_helper.rs
src/storage/trie/merkle_trie.rs
src/utils/cli.rs
src/utils/factory.rs

We were converting fids from u64 to u32 and back all over. Now we use u64 everywhere, except right before writing to the db and right after reading from it.
The original reason to use u32 was to save on disk space, this preserves the space savings but it's cleaner to deal with u64 everywhere.

Refactor fid type to use u64 everywhere

---

src/network/server.rs
src/storage/store/account/message.rs

Decode message bytes in `submit_message` rather than submitting messages with both `data` and `data_bytes` populated. This ensures that `data` is consistent with `data_bytes`.

decode message bytes in submit_message

---

src/network/admin_server.rs
src/proto/admin_rpc.proto

We need fnames in snapchain for the migration and an rpc to allow us to submit them. 
Tested this by running the migration with username proofs.

submit username proofs via admin rpc

---

src/network/server_tests.rs
src/storage/store/stores.rs

The `StoreType` names in hubs don't have the `STORE_TYPE` prefix. Manually translate the enum to strings to match hubs.

make store type names consistent with hubs

---

src/storage/trie/merkle_trie.rs

Use a prefix of 7 rather than 8 for fnames. This ensures we don't overlap with message type prefixes.

fix prefix for fname trie key

---

Cargo.lock
Cargo.toml

The 0.2.0 tag was removed when 0.3.0 was introduced. Remove the version and pin the dependency to a rev.

pin foundry dependency to a rev

---

src/bin/setup_local_testnet.rs
src/connectors/onchain_events/mod.rs
src/main.rs

Plumb real onchain events through to the engine and have them included in blocks. 
Tested by running local snapchain nodes and observing logs and made a small parallel change to switch local nodes to `127.0.0.1` ips.

ingest real onchain events

---

.github/workflows/verify.yml
src/core/types.rs
src/core/util.rs
src/storage/store/engine_tests.rs
src/utils/factory.rs

We were passing in farcaster time to on chain events, which caused the block number to be incorrect (derived from timestamp) and the revoke to be rejected.

Fix incorrect timestamp handling

---

src/storage/store/engine.rs
src/storage/store/engine_tests.rs
src/storage/trie/merkle_trie.rs
src/storage/trie/merkle_trie_tests.rs

Handle the fid = 0 and padding out usernames correctly. This should fix the trie crashes we see during fname ingestion.

fix fname processing

---

src/network/server.rs
src/proto/request_response.proto
src/proto/rpc.proto

Port the equivalent of the `GetSyncMetadataByPrefix` rpc from hubs. Here, there a trie per shard, so we specify the shard id in the request.

add rpc for trie inspection

---

src/storage/store/engine.rs

The transaction `summary` log tag is showing up as empty. Add counts of messages in the transaction and number of transactions to reconcile the information in this tag against.

add counts to trie mismatch logs

---

src/main.rs
src/mempool/mempool.rs
src/mempool/mempool_test.rs
src/mempool/mod.rs
src/network/server_tests.rs
tests/consensus_test.rs

Throw away messages that already exist in the trie in the mempool before forwarding to the engine.

add duplicate message validation to mempool

---

src/consensus/proposer.rs
src/main.rs
src/mempool/mempool.rs
src/mempool/mempool_test.rs
src/network/server.rs
src/network/server_tests.rs
src/node/snapchain_node.rs
src/perf/engine_only_perftest.rs
src/storage/store/engine.rs
src/storage/store/test_helper.rs
tests/consensus_test.rs

Pull messages out of the mempool and run validations at that point so all messages fed to the engine are likely to be valid.

pull messages out of mempool rather than pushing messages into engine

---

src/connectors/onchain_events/mod.rs

Return an error rather than panicking if an int conversion fails in the onchain events ingestion.

fix int overflow crash for onchain events

---

src/connectors/onchain_events/mod.rs
src/main.rs

Add stats to onchain events ingestion codepath.

add stats to onchain events ingestion

---

src/storage/store/engine.rs

These logs are pretty spammy-- we see them each time a node proposes, validates, or commits a transaction. Downgrade them to debug so they don't show up in datadog.

downgrade replayed transaction log to debug

---

src/storage/store/engine.rs
src/storage/store/engine_tests.rs

Look up ens proofs in the username proofs store rather than the user data store.

fix handling of ens usernames

---

src/storage/store/engine.rs
src/utils/factory.rs

`encode_to_vec` adds extra characters to the string and is not consistent with how the primary key is encoded on insert. Use `as_bytes` to translate the string to a vec of utf8 bytes.

fix ens name lookups to use correct encoding

---

src/mempool/mempool.rs
src/mempool/mempool_test.rs
src/storage/store/account/onchain_event_store.rs
src/storage/store/test_helper.rs

Switch from using the trie to the account store for the duplicate message check in the mempool.

use the message store for mempool validation

---

src/mempool/mempool.rs
src/storage/store/account/message.rs

The mempool raises when it sees a message type that it can't translate to a set postfix for an account store. Log an error and proceed rather than raising in this case.

return an error rather than raising for invalid message type

---

.github/workflows/verify.yml
Cargo.lock
Cargo.toml
Dockerfile
src/connectors/onchain_events/mod.rs
src/core/validations.rs
src/network/server.rs
src/network/server_tests.rs

Contract signature validation was woefully complex, and hubs didn't handle all the cases properly. The eth-signature-verifier library does, but uses old alloy versions. I forked it (https://github.com/CassOnMars/eth-signature-verifier), and have that in place now.

fix: handle contract signatures correctly, move support to server

---

src/network/server.rs

This logging is really spammy during the migration. Remove it for now and add it back later if we decide that we need it.

remove submit message logging in rpc server

---

src/storage/db/rocksdb.rs

Use LZ4 for DB compression as it is [recommended by RocksDB](https://github.com/facebook/rocksdb/wiki/Compression#configuration) and has slightly faster performance characteristics and a slightly better compression rate.
Hopefully it is easier to make this change now than it was on the old hub monorepo 😄

perf: Use LZ4 for DB compression

---

src/network/server.rs
src/storage/store/account/store.rs
src/storage/store/engine_tests.rs

The account stores and trie were inconsistent for link compaction messages because we don't emit `deleted_messages` and we update the trie based on the data in the event. This led to the storage usage calculations being inconsistent across hubs and snapchain.

include deleted messages in emitted hub event for link compactions

---

src/consensus/proposer.rs
src/core/message.rs
src/main.rs
src/mempool/mempool.rs
src/mempool/mempool_test.rs
src/network/gossip.rs
src/network/gossip_test.rs
src/network/server_tests.rs
src/node/snapchain_node.rs
src/perf/engine_only_perftest.rs
src/proto/blocks.proto
src/storage/store/engine.rs
tests/consensus_test.rs

This PR adds a basic implementation of the gossipped mempool described in #180.
It uses the existing mempool implementation but changes the key to use a key derived from the timestamp and identity of a message. Additions to the mempool are broadcast using a new gossip message. Messages are also evicted from the mempool when shard chunks are emitted that contain messages contained in the mempool.
Some minor changes to the channels and overall plumbing was required to setup the mempool communication.

feat: Add gossip and eviction to the mempool

---

src/main.rs
src/mempool/mempool.rs
src/mempool/mempool_test.rs
src/network/server_tests.rs
src/perf/engine_only_perftest.rs
tests/consensus_test.rs

We keep dropping messages in the mempool during backfills. Allow unlimited mempool size for backfills.

allow unlimited mempool size

---

src/network/gossip.rs

Sync RPC calls are failing because they are considered duplicate messages. We don't need duplicate message protection for consensus topics. We should only have this for the mempool.

Disable message id for gossip

---

src/connectors/onchain_events/mod.rs
src/main.rs
src/mempool/mempool.rs
src/mempool/mempool_test.rs
src/network/admin_server.rs
src/network/server_tests.rs
src/perf/engine_only_perftest.rs
tests/consensus_test.rs

Currently we drop things in the mempool when the mempool is at capacity but other parts of the system are unaware that messages are being dropped in the mempool. Block the mempool rx channel when the mempool is full so that the components of the system sending messages to the mempool can react appropriately upon learning that the mempool is full.

block mempool tx channels when the mempool is at capacity

---

src/connectors/fname/mod.rs
src/connectors/onchain_events/mod.rs
src/proto/node_state.proto
src/storage/store/node_local_state.rs

There are a few bugs in the onchain event ingest persistence: 
1. We don't store the last block number by contract but we ingest by event type for the initial sync 
2. We use the onchain events persistence for fname transfers.
This feature fixes both.

fix onchain event persistence

---

src/mempool/mempool.rs
src/mempool/mempool_test.rs

Right now, the mempool always stays very small. This points to us not reading in messages as quickly as we're reading them out. Make the poll interval configurable so we can play around with how fast we read messages in.

make mempool poll interval configurable

---

src/connectors/fname/mod.rs
src/connectors/onchain_events/mod.rs
src/storage/store/node_local_state.rs

Fix onchain event ingest to persist a block number for historical sync only after all event types have been ingested for that block number. Fix fname ingest to persist the latest username proof rather than block numbers.

bugfixes for onchain events and fname ingest persistence

---

src/bin/submit_message.rs
src/connectors/fname/mod.rs
src/connectors/onchain_events/mod.rs
src/consensus/consensus.rs
src/mempool/mempool.rs
src/mempool/mempool_test.rs
src/network/admin_server.rs
src/network/gossip.rs
src/network/gossip_test.rs
src/network/server.rs
src/perf/engine_only_perftest.rs
tests/consensus_test.rs

- Bring back content id for non consensus topic gossip messages, to prevent duplicate messages from flooding the network
- Add a check to the mempool to prevent sending messages back to gossip that were received from gossip
This caused nodes to infinitely send mempool messages back and forth to each other

fix: Fix mempool infinitely rebroadcasting messages via gossip

---

src/consensus/malachite/host.rs
src/consensus/proposer.rs

We currently try to commit synced values twice because malachite calls `decide` internally and we call `decide` on seeing a synced value.

don't call decide on synced values

---

Cargo.lock
src/connectors/fname/mod.rs
src/tests/cfg_test.rs

Remove stop id requirement so we can continually read fname transfers

fix: Remove stop id requirement for fnames

---

src/bin/setup_local_testnet.rs
src/connectors/onchain_events/mod.rs
src/main.rs
src/mempool/mempool.rs
src/mempool/mempool_test.rs
src/network/gossip.rs
src/network/gossip_test.rs
tests/consensus_test.rs

Tested that rpcs to read nodes work and submitting messages to read nodes works in cluster 2. 
```
grpcurl -plaintext -proto src/proto/rpc.proto -import-path src/proto 10.0.0.126:13383 HubService/GetInfo
{
"dbStats": {
"numMessages": "234569",
"numFidRegistrations": "1623",
"approxSize": "138420435"
},
"numShards": 2,
"shardInfos": [
{
"maxHeight": "199",
"approxSize": "174681"
},
{
"shardId": 2,
"maxHeight": "417",
"numMessages": "117152",
"numFidRegistrations": "810",
"approxSize": "69121768"
},
{
"shardId": 1,
"maxHeight": "417",
"numMessages": "117417",
"numFidRegistrations": "813",
"approxSize": "69298667"
}
]
}
```

enable rpc server and http server for read nodes

---

src/consensus/consensus.rs
src/consensus/malachite/read_host.rs
src/consensus/malachite/read_node_actors_test.rs
src/consensus/malachite/read_sync.rs
src/consensus/malachite/spawn_read_node.rs
src/main.rs
src/network/gossip.rs
src/node/snapchain_read_node.rs
tests/consensus_test.rs

New blocks can't be processed until earlier ones are synced. Don't start processing new blocks until we're almost done syncing historical blocks.

read nodes subscribe to decided blocks only after initial sync is done

---

src/consensus/read_validator.rs
src/main.rs
src/network/gossip.rs

A couple small fixes for read nodes: 
- account for block shard in the number of shard we wait on before triggering subscription to live decided values
- bump logging for processed blocks/shard chunks to info because these logs are very useful for understanding if the read node is actually progressing

read node fixes

---

src/bin/setup_local_testnet.rs
src/cfg.rs
src/main.rs
src/network/admin_server.rs
src/storage/db/snapshot.rs

1. Use config files for AWS credentials. Using the default AWS envvars conflicts with our deploy process. 
2. Move the snapshot upload to a background thread so it doesn't block the rpc from returning. 
3. Use multipart upload. The regular `put_object` api call was failing often.

fixes for snapshot upload

---

src/connectors/fname/mod.rs
src/connectors/onchain_events/mod.rs
src/main.rs
src/storage/db/rocksdb.rs
src/storage/db/snapshot.rs
src/tests/cfg_test.rs

Enable and snapshot download on startup. 
- Switched back from multipart upload to `put_object` because multipart upload was causing issues with decompression
- It's key to decompress the chunks into a single file before unpacking
- Added support for resuming onchain event/fname ingest from current place because past data should be included in blocks already. 
Did a lot of manual testing locally and on cluster 2:
- Started a validator node from snapshot
- Started a read node from snapshot

enable snapshot download

---

src/consensus/malachite/host.rs

There's a lot of unnecessary network spam if all validators publish decided values to read nodes.

only publish decided values if you're the proposer

---

src/consensus/consensus.rs
src/consensus/malachite/spawn.rs
src/consensus/validator.rs

Timeouts should be smaller than the defaults.

perf: Reduce malachite step timeouts to be in line with faster blocktimes

---

Cargo.lock
Cargo.toml

foundry nightly is producing issues with eth-signature-verifier, and is no longer needed to work anyway. 0.3.6 no longer depends on it, bumping the package version

fix: bump eth-signature-verifier

---

src/consensus/proposer.rs
src/consensus/validator.rs
src/storage/db/rocksdb.rs
src/storage/store/engine.rs
tests/consensus_test.rs

Each node replays the transactions twice, once either in propose or validate and then once more in decide. Caching and replaying on decide will save about ~30% of the time spent by the node to decide a height. With 1K msgs/block it takes:
~300ms to propose + 300 ms to validate + 300 ms to validate again + ~25ms to commit
This change will bring it down to ~625ms from ~925ms.

perf: Cache transaction on propose and validate to replay on commit

---

src/mempool/mempool.rs
src/mempool/routing.rs
src/network/server.rs
src/network/server_tests.rs
src/storage/trie/merkle_trie.rs
src/storage/trie/merkle_trie_tests.rs
src/storage/trie/trie_node.rs
src/storage/trie/trie_node_tests.rs

Add a "virtual" shard id as the first byte of the trie key for messages so when we need to reshuffle fids among the blockchain shards, we don't have to move every single fid root individually. We can just remap the 256 virtual shards to actual physical shards.
There was an unexpected complication with an implicit assumption that the `TIMESTAMP_LENGTH` (really the `UNCOMPACTED_LENGTH`) of the trie matches the number of nibbles in the trie key for a message type due to the branching factor.

feat: Add virtual shard id to fids in the merkle trie to make re-sharding easier

---

src/storage/store/account/event.rs
src/storage/store/account/on_chain_event_store_tests.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs
src/storage/store/stores.rs
src/storage/store/test_helper.rs

Change event ids to use block numbers instead of timestamps, so it's consistent everywhere.

feat: Switch event id to use block numbers instead of timestamps

---

src/consensus/malachite/host.rs
src/consensus/validator.rs

Validators were trying to maintain the block time even when catching up via sync.

fix: Don't enforce block time validator is syncing

---

src/core/util.rs
src/mempool/mempool.rs
src/mempool/mempool_test.rs

Prioritize processing onchain events and fname transfers so that we don't reject user messages due to missing onchain events.

fix: expedite processing of validator messages through mempool

---

src/connectors/onchain_events/mod.rs

Temporary connectivity issues should not halt onchain event processing
Tested manually

fix: Add retries for onchain events

---

src/main.rs
src/network/server.rs
src/network/server_tests.rs
tests/consensus_test.rs

Temporarily disable public mempool access until after mainnet is caught up

feat: Disable mempool publish from non-validators nodes until after backfill

---

src/mempool/mempool_test.rs

seeing some test flakes eg: https://github.com/farcasterxyz/snapchain/actions/runs/14009791469/job/39228145671?pr=330
seems tests have their own port but 9304 was shared with test_mempool_prioritization, likely causing this

chore: change port to unique port in test_mempool_eviction

---

src/connectors/onchain_events/mod.rs
src/main.rs
src/network/admin_server.rs
src/proto/admin_rpc.proto

We dropped some onchain events during the initial sync and need an admin rpc to retrigger ingest for the range we missed. 
Tested locally. 
```
❯ grpcurl -plaintext -proto src/proto/admin_rpc.proto -d '{"fid" : 1030970}' -import-path src/proto 127.0.0.1:3383 AdminService/RetryOnchainEvents
{}
❯ grpcurl -plaintext -proto src/proto/admin_rpc.proto  -d '{"block_range": {"start_block_number" : 133577805, "stop_block_number": 133577810}}' -import-path src/proto 127.0.0.1:3383 AdminService/RetryOnchainEvents
```
```
2025-03-26T03:50:14.112717Z  INFO snapchain::connectors::onchain_events: Starting l2 events subscription latest_block_on_chain=133681118 latest_block_in_db=133669197
2025-03-26T03:50:23.013693Z  INFO snapchain::connectors::onchain_events: Retrying onchain events for fid fid=1030970 …
```

feat: admin rpc to retry onchain events by fid and block range

---

Cargo.lock
Cargo.toml
src/network/server.rs
src/network/server_tests.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs

Reduces excessive logging on invalid messages and returns the store error back to the caller so they can handle appropriately.

fix: Return store errors on simulate and avoid logging

---

src/consensus/malachite/network_connector.rs
src/main.rs

We seem to be dropping the listening events in the malachite consensus engine sometimes. Start gossip last, after consensus actors are ready to see if it helps.

fix: Potential fix for shards not starting consensus

---

src/consensus/mod.rs
src/consensus/proposed_values_test.rs
src/consensus/proposer.rs

We're leaking memory in `proposed_blocks` and `proposed_shard_chunks` by not removing proposed values for older heights and rounds.

fix: stop tracking proposals that will never be used again

---

src/consensus/proposed_values_test.rs
src/consensus/proposer.rs

Previously we were only removing proposals for the decided height, assuming it'd be rare to have proposals stored for different heights. In practice, we continue to see the pending proposals grow so we are switching to remove all old proposals on each decide.

fix: remove all stale proposals on decide

---

src/core/validations/message.rs
src/core/validations/message_test.rs
src/storage/store/engine_tests.rs
src/utils/factory.rs

Link compact messages can exceed the allowed 2048 bytes. The max size of a link compact state message I could find was ~61kB so set the max to something a bit higher than that.

fix: allow larger message size for link compact messages

---

src/mempool/mempool.rs

Increase the default mempool size to 1M to be conservative.

chore: increase default mempool size

---

src/main.rs
src/storage/store/stores.rs
src/storage/store/stores_test.rs

Event and shard pruning jobs can run into each the first time they are run. Add a lock to prevent this.

fix: Ensure pruning jobs don't run into each other

---

src/network/server.rs
src/network/server_tests.rs
src/storage/store/engine.rs

Hubs allow subscription without authentication.

fix: Remove auth requirement for subscribe endpoint

---

docker-compose.mainnet.yml
docker-compose.testnet.yml

Enable snapshot download for read nodes by default.

chore: enable snapshots for read nodes

---

src/consensus/malachite/read_node_actors_test.rs
src/consensus/malachite/spawn_read_node.rs
src/consensus/read_validator.rs
src/consensus/read_validator_test.rs
src/consensus/validator.rs
src/node/snapchain_read_node.rs
src/storage/store/test_helper.rs

Verify commit signatures when a read validator processes decided values. This verifies the signatures of the decided values and that the signers are expected for the height.

feat: Verify commit signatures when processing decided values

---

docker-compose.testnet.yml
src/network/server.rs
src/network/server_tests.rs
src/proto/request_response.proto

Subscribe call is not backwards compatible with existing clients because the sequence id changed on the protobuf, keep it the same. And some other minor fixes.

fix: Keep subscribe shard index backwards compatible

---

src/network/gossip.rs
src/network/gossip_test.rs

If we're disconnected from any of the bootstrap peers, try to reconnect.

fix: retry connections to bootstrap peers

---

.gitignore
src/core/error.rs
src/network/server.rs
src/network/server_tests.rs

Return consistent error messages when submitting a message. Also return the error code as a separate field in the metadata

feat: Return error codes in standard format on submit

---

src/connectors/fname/mod.rs
src/connectors/onchain_events/mod.rs
src/network/server.rs
src/utils/statsd_wrapper.rs

It would be nice to see how bursts of submit message requests are processed by the server.

chore: add metrics for the number of concurrent submit_message requests

---

src/core/message.rs
src/core/validations/error.rs
src/main.rs
src/network/http_server.rs
src/network/server.rs
src/network/server_tests.rs
src/proto/hub_event.proto
src/proto/request_response.proto
src/storage/store/account/onchain_event_store.rs
src/storage/store/account/store.rs
src/storage/store/account/user_data_store.rs
src/storage/store/account/username_proof_store.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs
src/storage/store/test_helper.rs
src/utils/factory.rs
tests/consensus_test.rs

Add a new HubEvent type for merge failures that contains the error code and reason why message failed to be merged. This is useful for clients who submit messages which were included into the mempool, but then failed later.
Also updates some api error messages to be consistent with hubs, as well as return some additional fields in `GetInfo` and `HubEvent`

[feat] Add new event type for merge failures

---

src/network/http_server.rs

Add submit message http endpoint. 
https://github.com/farcasterxyz/snapchain/issues/381
Tested submitting message to a local node with auth. It was received but failed validation which means the endpoint is working. 
`{"error":"Failed to submit message","error_detail":"status: InvalidArgument, message: \"bad_request.validation_failure/Invalid message hash\", details: [], metadata: MetadataMap { headers: {\"x-err-code\": \"bad_request.validation_failure\"} }"}`

feat: add submitMessage http endpoint

---

src/network/server.rs
src/network/server_tests.rs

We currently start from the earliest event when `fromId` is not specified. Hubs start from the latest and this is what we should do. 
https://github.com/farcasterxyz/snapchain/issues/387

fix: start subscribe rpc from latest event if from_id is not specified

---

src/network/http_server.rs

We were requiring pageToken to be provided as a byte array rather than a string, which makes it very hard(impossible?) to construct a url with a pageToken.
https://github.com/farcasterxyz/snapchain/issues/393

fix: parse pageToken as strings for http api

---

src/network/http_server.rs

Test locally with the following:
```
curl -X GET "http://localhost:3381/v1/userNameProofByName?name=dwr.eth" -H "Content-Type: application/json"
{"timestamp":1690215011,"name":"dwr.eth","owner":"0xd7029bdea1c17493893aafe29aad69ef892b8ff2","signature":"yt1O0MN7I3dRA+fAin4N1T8DsIoOm+FsQ/RplKVdUkpXxBxclDM7AtO/5z29JNEkxc7UP2Lm4XSvieonDdeBgRs=","fid":3,"type":"USERNAME_TYPE_ENS_L1"}
```
Closes #396

refactor: change `UserNameProof` type to string

---

src/network/http_server.rs

Looks like there just wasn't a struct defined in the `http_server.rs` so defined that and made sure that it handles the renames as expected. Sorry again for missing this!
Tested by building locally and attempting to hit the endpoint with:
```
curl -X GET "http://localhost:3381/v1/linksByFid?fid=12345&link_type=follow&pageSize=1&reverse=true" -H "Content-Type: application/json" 
{"messages":[{"data":{"type":"MESSAGE_TYPE_LINK_ADD","fid":12345,"timestamp":107114580,"network":"FARCASTER_NETWORK_MAINNET","linkBody":{"type":"follow","displayTimestamp":null,"targetFid":43}},"hash":"0x74955c7c8c44e5788ef8a0a3a341ec6fac199cb1","hashScheme":"HASH_SCHEME_BLAKE3","signature":"PY+pvwfhnAH8BQajcIcj88w1JkhV4xSg723G4d9vfo+CKfP8sfZ41MLG6v2J4FKjJYRPa4zkPp8AKaNP3cr4BA==","signatureScheme":"SIGNATURE_SCHEME_ …
```

fix: add `struct` for `LinksByFidRequest` in `http_server`

---

src/network/server.rs
src/network/server_tests.rs
src/storage/store/engine_tests.rs
src/storage/store/test_helper.rs
src/utils/factory.rs

Return fname proofs via the username proof apis. 
Closes https://github.com/farcasterxyz/snapchain/issues/391
Tested manually on testnet.

fix: have username proof apis return proofs for fnames

---

src/network/http_server.rs

We really want `default` wherever we have `skip_serializing_if` for the request types. We never serialize these types--we only deserialize them and we want to default to `None` if these fields are missing. 
Right now we error if `pageToken` is not specified but we want such a request to go through.

fix: allow http urls to be missing query parameters for optional fields

---

src/network/gossip.rs

Read nodes are struggling to connect to bootstrap peers so they're not syncing.

fix: increase gossip connection limits 

---

src/network/gossip.rs

Nodes are getting stuck on sync after connecting to "bad peers". Disable peer autodiscovery til we can diagnose further.

fix: stop dialing discovered peers by default

---

src/consensus/malachite/network_connector.rs

We might be dropping messages because the default output port size is too small. Increase it to 100 to see if sync requests stop timing out.

fix: Increase output port capacity so we don't lose messages

---

src/consensus/malachite/host.rs

We're receiving sync requests but not responses. Log whether we try to retrieve decided values to determine if the request gets dropped before or after this.

chore: add more logging for sync

---

src/consensus/consensus.rs
src/consensus/malachite/spawn.rs
src/consensus/malachite/spawn_read_node.rs
src/network/gossip.rs

Noticing that our validators are taking just over a second to return sync values. So increase the request timeout to 2 seconds.
Also, have read nodes dial validators if they have too few peers, instead of waiting until they have 0.

fix: Increase sync timeout and let read nodes connect to more validators

---

src/network/gossip.rs

- Reduce gossip heartbeat to be more inline with target block time
- Increase D values (validators having too few connections may be impacting sync since read nodes are only connected to validators right now)
- Add logging for dial and rpc failures
I think heartbeat hasn't caused issues until now because the validator set is so small, but heartbeat should be lower than block time (or we should use floodsub for consensus)

fix: Tune gossip params

---

src/consensus/malachite/host.rs

Sleeping to wait for the block delay blocks us from processing sync messages which delays sync on other nodes.

fix: make the sleep in consensus critical path async

---

src/consensus/malachite/read_node_actors_test.rs
src/consensus/malachite/read_sync.rs

Previously we were syncing against any node that we received a status update for even if we weren't necessarily connected to that node. This caused sync timeouts.

fix: read nodes only attempt sync against connected peers

---

src/network/server.rs

Also includes a fix on how next page token is handled but won't work as expected until after #421 gets merged in. Tested locally:
```curl -X GET "http://localhost:3381/v1/reactionsByTarget?url=chain://eip155:1/erc721:0x39d89b649ffa044383333d297e325d42d31329b2" -H "Content-Type: application/json"```
```
{
"messages": [
{
"data": {
"type": "MESSAGE_TYPE_REACTION_ADD",
"fid": 1134,
"timestamp": 79752856,
"network": "FARCASTER_NETWORK_MAINNET",
"reactionBody": {
"type": "REACTION_TYPE_LIKE",
"targetUrl": "chain://eip155:1/erc721:0x39d89b649ffa044383333d297e325d42d31329b2"
}
},
"hash": "0x94a0309cf11a07b95ace71c62837a8e61f17adfd",
"hashScheme": "HASH_SCHEME_BLAKE3",
"signature": "+f/+MKKp1JBDu0IHbyF9mq2BzSkT7/tBZ7kVqAkwjanXqIZVl/aaxJ24EdkM/QyPkQcC3femJhnPuZ0Uqzd0Ag==",
"signatureScheme": …
```

fix: make reaction type optional for `get_reactions_by_target`

---

site/docs/pages/whitepaper.mdx

Add a protocol upgrades section to the docs that explains how breaking changes will work

docs: Add a section on protocol upgrades

---

src/network/http_server.rs
src/network/server.rs
src/network/server_tests.rs
src/proto/request_response.proto
src/storage/store/account/onchain_event_store.rs

Implement `GetFids` and `v1/fids` which was previously stubbed out. I've tried to follow the established patterns as much as possible for constructing `next_page_token` etc. I also had to modify `get_onchain_events` to allow requests that aren't tied directly to fids.
Closes https://github.com/farcasterxyz/snapchain/issues/392

feat: Add GetFids API

---

src/network/gossip.rs
src/network/gossip_test.rs
src/storage/store/account/message.rs

This lets clients handle messages with both data and dataBytes populated for convenience.

fix: Prirotize data_bytes on message when both data and data_bytes are set

---

src/network/http_server.rs

HTTP method for validateMessage should be POST and not GET
Tested locally.
Report https://warpcast.com/ds8/0xfd337116

fix: Fix validateMessage http method

---

Dockerfile

Adjusted reference to newer eth-signature-verifier commit hash – not only should we do that anyway (for safety), it resolves the docker build issue by skipping over the need to use build.rs bash invocation wizardry.

fix: update eth-signature-verifier to use version with static build outputs

---

src/core/validations/error.rs
src/core/validations/message.rs
src/core/validations/message_test.rs
src/utils/factory.rs

We were returning valid every time`validate_message` is called with a frame action. This is incorrect- we should validate the frame action as we do in hubs.

fix: validate frame action body

---

src/network/http_server.rs

We aren't serializing frame action messages to send back to the user and instead returning an error when they are submitted via `validateMessage`. Fix by serializing frame action messages. 
Tested locally

fix: handle frame actions in http server

---

src/main.rs
src/storage/db/snapshot.rs

There are cases where our code for detecting whether we should download a snapshot doesn't work-- e.g. if someone has db directory with other files/folders. Rather than figuring out what all these cases are, add a config option to override this detection logic and download snapshots.

chore: add config option for forcing download from snapshot

---

src/network/server.rs
src/network/server_tests.rs
src/storage/store/account/onchain_event_store.rs
src/storage/store/engine.rs

Implements `get_id_registry_on_chain_event_by_address`
I fought with how to handle the `get_onchain_events` we could alternatively make the `fid` on that optional but I didn't want to mess with the existing interfaces too much. I also initially added an iterator on the events but backtracked on that since it didn't seem right but you can see if in the previous commits. I ended up adding a `get_all_onchain_events` which doesn't take an FID at all. If we'd prefer to make the `fid` optional on the existing function I can do that.
I added a test and it's passing but we might want to put the iterator through the ringer a little more. Also callout I did not test this with complete production state so I don't know how much this will effect latency on a cold get before the cache spins up so that …

fix: `getidregistryonchaineventbyaddress`

---

src/mempool/mempool_test.rs
src/network/server.rs
src/network/server_tests.rs
src/perf/gen_multi.rs
src/perf/gen_single.rs
src/storage/store/account/onchain_event_store.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs
src/storage/store/test_helper.rs
src/utils/factory.rs
tests/consensus_test.rs

Since we're adding auth addresses, we should be careful to not treat auth addresses like signers when we only care about signers.

fix: make sure to check key_type for signers

---

src/storage/store/account/onchain_event_store.rs

Fix pagination for `get_on_chain_signers_by_fid`. Previously we were using the paged rocksdb iterator which doesn't compose well with custom filtering.

fix: fix pagination for get_on_chain_signers_by_fid

---

src/core/validations/cast_test.rs
src/core/validations/link_test.rs
src/core/validations/reaction_test.rs

We have some validation tests that query from live hubs. Move them to query from snapchain.

fix: update tests that depend on hubs being up

---

src/storage/store/engine.rs

We introduced a change to check key type on signer revokes that's invalid. Remove this check-- key_type is always 0.

fix: process signer revoke messages as expected

---

src/jobs/snapshot_upload.rs
src/network/admin_server.rs
src/proto/admin_rpc.proto

This allows us to manually retry just 1 shard rather than all of them.

chore: add ability to upload snapshot just for 1 shard

---

src/consensus/malachite/spawn.rs

The malachite consensus metrics were never registered in the global registry.

fix: register malachite consensus metrics in registry

---

src/consensus/malachite/read_node_actors_test.rs
src/consensus/proposer.rs
src/consensus/read_validator_test.rs
src/mempool/rate_limits_test.rs
src/network/server_tests.rs
src/perf/engine_only_perftest.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs
src/storage/store/test_helper.rs
src/version/version.rs

Set up version schedule for upcoming protocol release on June 16 2020. Main features are Farcater pro, basenames and a few protocol level bug fixes

feat: Setup version schedule for next protocol release

---

src/network/http_server.rs

Add tier subscriptions to the http api to bring it to parity with the grpc api.

fix: add tier subscriptions to http api

---

.gitignore
src/network/http_server.rs
src/network/server.rs
src/network/server_tests.rs
src/proto/request_response.proto
src/proto/rpc.proto

Add GetFidAddressType endpoint for unified address validation as reference in https://github.com/farcasterxyz/snapchain/issues/529
Adds a new `GetFidAddressType` endpoint that checks if an address is valid as a custody address, auth address, or verified address in a single API call.
Currently, SIWF (Sign-In With Farcaster) authentication requires racing multiple API calls to check if an address is valid:
- Check IdRegistry for custody addresses
- Check KeyRegistry for auth addresses (keyType=2)
- Check verified addresses
This is inefficient and adds unnecessary complexity.
New endpoint `GetFidAddressType(fid, address)` returns:
```proto
{
is_custody: boolean,   // Address owns the FID (IdRegistry)
is_auth: boolean,      // Address is an auth key (KeyRegistry keyType=2)
is_verified: …
```

feat: unified fid address type endpoint

---

src/network/http_server.rs

Show the correct onchain event type for tier purchase events in the http api.

fix: show onchain event type for tier purchase in http api

---

src/mempool/mempool.rs
src/mempool/mempool_test.rs
src/utils/factory.rs

The mempool duplicate message check is a performance optimization. Onchain events and fname transfers are not that frequent, and don't benefit from this. The engine is capable of handling duplicates.
This check was prevent fname transfers from being recorded correctly, because it was checking if the name proof existed at all, and was not specific to the fid.

fix: Mempool should not do duplicate checks for validator messages

---

src/network/http_server.rs
src/network/server_tests.rs
src/proto/hub_event.proto
src/storage/store/account/event.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs

#544
Adds a "block confirmed" event to signal block finalization.
This event includes block metadata such as number, hash, timestamp, and total event count.

feat: Add Block Confirmed event type as the first event emitted for a block

---

src/storage/store/engine.rs

This is a much clearer indication of how far behind a node is than block height.

chore: emit block delay metric

---

src/connectors/onchain_events/mod.rs

Was calculating the incorrect current time.

fix: calculate onchain events delay metric correctly

---

src/network/server_tests.rs
src/storage/store/account/onchain_event_store.rs

Previously we were returning all signers, even removed ones, which is incorrect.

fix: make GetOnChainSignersByFid endpoint only return active signers

---

src/version/version.rs

Bump protocol version to 3 for Engine version 6 (tied to storage redenomination)

chore: Bump protocol version for storage re-denomination

---

src/network/http_server.rs

Properly validate and throw when `targetFid` is not passed for `linksByTargetFid`. The `link_type` parameter is validated later so we don't need to do it here.
Fixes https://github.com/farcasterxyz/snapchain/issues/557

fix: Properly validate `targetFid` param in `linksByTargetFid`

---

src/network/server_tests.rs
src/storage/store/account/on_chain_event_store_tests.rs
src/storage/store/account/onchain_event_store.rs
src/storage/store/engine.rs
src/storage/store/stores.rs
src/storage/store/stores_test.rs

This activates the new storages limits a few days ahead of mainnet so we can test everything works as intended.
We can't use the EngineVersion for for this because we want to rely on onchain event block timestamps and not Farcaster block timestamps.

feat: Activate the storage unit redenomination a few days earlier on testnet

---

src/main.rs
src/network/gossip.rs
src/network/http_server.rs
src/network/server.rs
src/network/server_tests.rs
src/proto/request_response.proto
src/proto/rpc.proto
tests/consensus_test.rs

Add RPC endpoint for getting the currently connected peers. To do this, introduces a `BTreeMap` in `SnapchainGossip` that stores the contact info received from other peers.

feat: Add endpoint for connected peers

---

src/mempool/mempool_test.rs
src/network/server_tests.rs
src/storage/store/account/on_chain_event_store_tests.rs
src/storage/store/account/onchain_event_store.rs
src/storage/store/test_helper.rs
src/utils/cli.rs
src/utils/factory.rs
tests/consensus_test.rs

Storage unit related tests broke in `server_tests.rs` after the cutoff hit for Testnet and new units were being detected as 2025 units rather than 2024 units. Update the logic to generate storage rent events so callers have to explicitly specify a storage unit type.

fix: fix broken storage unit related tests

---

.github/workflows/verify.yml
Cargo.lock
Dockerfile
src/network/gossip.rs

Add the ability for nodes to set direct peers. Validators should set each other as direct peers.

feat: add direct peers config for gossip

---

src/main.rs
src/storage/db/snapshot.rs

Fixes https://github.com/farcasterxyz/snapchain/issues/560
This fetches all metadata in one go and makes it compatible with snapdown so that it's possible to use snapdown to resume broken downloads.
Also add a check to make sure the downloaded file size matches the content length similar to snapdown so we catch and retry file corruption early.

feat: Make snapshot metadata compatible with snapdown

---

.gitignore
site/docs/pages/reference/grpcapi/message.md
site/docs/pages/reference/httpapi/message.md
src/network/http_server.rs
src/network/http_server_test.rs
src/network/server.rs
src/network/server_tests.rs
src/proto/rpc.proto

Add the SubmitBulkMessages API (which had been commented out). 
The endpoint (both grpc and http API) accepts an array of messages, and submits them sequentially. Right now, the messages need to be independent (i.e., a message that depends on a previous message in the array to succeed is not supported yet)
It will attempt to merge all the messages, and return success/failure for each one individually

feat: Add SubmitBulkMessages rpc/http API

---

src/network/server.rs
src/storage/store/account/cast_store.rs
src/storage/store/account/link_store.rs
src/storage/store/account/reaction_store.rs
src/storage/store/account/store.rs
src/storage/store/account/user_data_store.rs
src/storage/store/account/username_proof_store.rs
src/storage/store/account/verification_store.rs
src/storage/store/engine.rs
src/storage/store/engine_tests.rs
src/version/version.rs

Allow dependent messages during bulk submit. 
Dependent messages are when one message in the array of messages being submitted depends on an earlier message in the same array. For eg., submitting a `[ENS proof , UserDataAdd]` message[] , which allows both messages to be accepted and submitted in one go.  See the `test_simulate_bulk_messages_username_proof_and_set` for an example 
The main change is here is to pass the DB txn all the way down the stores, so that they can use the current transaction + DB (instead of just the DB) to validate/process messages. 
This PR allows ENS proofs to be submitted along with their dependent messages. (Other types of dependent messages (onchain events, verifications, fnames etc....) are in a separate PR

feat: Allow multi message simulation with dependent messages

---

src/main.rs
src/node/snapchain_read_node.rs
src/storage/store/engine.rs
tests/consensus_test.rs

When read-only nodes ingest a block, there is never a cached transaction, so there's no need to show this warning for read-only nodes.

fix: Suppress the "No valid cached transaction to apply" warning for read-only nodes

---

src/storage/store/account/reaction_store_test.rs
src/storage/store/account/user_data_store_test.rs
src/storage/store/account/verification_store_test.rs

We were using wrapping add/subtract functions which could wrap to 0/255 and cause incorrect behavior in the tests.

fix: fix tests to increment and decrement hash values correctly

---

src/version/version.rs

Protocol version 3 actually activated at 1752099061 on tesnet due to a delayed deploy. Fix the timestamp so validations will pass when syncing.

fix: Fix testnet version schedule to reflect when upgrade actually happened

---

src/replication/replication_engine.rs
src/replication/replication_engine_tests.rs
src/replication/replicator.rs
src/storage/store/account/onchain_event_store.rs

There was an issue with the replicator cursor getting stuck, and returning the same messages over and over again. Somewhat nuanced, but here's Claude's description of the problem:
The main issue was that the FIDs can have 1 register, but multiple transfer events. They are all indexed as OnChainEventType::EventTypeIdRegister on chain events, but this captures both register and transfer events. In the FidIterator, we're iterating over this event to get FIDs, but this also inadvertently captures transfer events, making multiple duplicate FIDs appear in the iterator. We need to filter more strictly in FidIterator::fetch()

fix: Handle replicator cursor gets stuck

---

src/storage/store/migrations/mod.rs

Supress the log message until we actually run the migrations

fix: Supress version check log message

---

src/replication/replication_stores.rs
src/storage/store/account/onchain_event_store.rs

Some FIDs have duplicate IDRegister events, so we shouldn't be returning duplicate FIDs based on that.

fix: Don't return duplicate FIDs

---

tests/consensus_test.rs

- Bump the per-step timeouts back to the defaults. Tests were regularly exceeding 250ms for the proposal step and were then timing out and dropping the messages included in the timed out proposals. This was causing the test failures. 
- Have the read node test wait for the read nodes to receive the desired shard chunks and not just the validators.

fix: fix consensus tests

---

src/storage/store/account/cast_store.rs
src/storage/store/account/cast_store_test.rs
src/storage/store/account/link_store.rs
src/storage/store/account/link_store_test.rs
src/storage/store/account/onchain_event_store.rs
src/storage/store/account/reaction_store.rs
src/storage/store/account/store.rs
src/storage/store/account/user_data_store.rs
src/storage/store/account/username_proof_store.rs
src/storage/store/account/verification_store.rs
src/storage/store/stores.rs

Allow stores to be created in a "conflict-free" mode, which allows duplicates to be inserted (overwritten) and allows conflicting messages with link_compact. The merging does not return an error, and the DB keys are overwritten and re-inserted into the Trie. Some "conflicting" messages - messages that are valid, but would be detected as either prunable or duplilcates are allowed (eg. Duplicate ID Register events). 
These messages are rare, but during replication we accept duplicate or prunable messages since they are in the Merkle Trie.

feat: Allow conflict-free stores for replicator

---

src/storage/db/rocksdb.rs

The paged iterator needs to add [0] to the page_token so that it captures any sub-keys, instead of increment_u8 which will skip over all sub keys during iteration

fix: Paged iterator doesn't go through sub-keys

---

src/consensus/proposer.rs

Add metric to track the last height included in a shard witness for each shard.

chore: add metric for confirmed shard heights

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Mint v0.6.0 for protocol release.

chore: mint new minor version v0.6.0

---

src/storage/constants.rs
src/storage/trie/errors.rs
src/storage/trie/merkle_trie.rs
src/storage/trie/merkle_trie_tests.rs
src/storage/trie/trie_node.rs
src/storage/trie/util.rs

Add a method that will do paged iteration over the trie. 
- Support paging at a arbitrary sub-tree. 
- This is used to iterate over all keys in a virtual trie shard("vts")
- Generate page_token/ start from next_page_token so that all keys are covered
- The page_token is complex Vec<Vec<>>, so encode/decode it to a base64 string
- Tests
Also this PR removes the attach_to_root and the recalculate_hash since we don't need it anymore - We'll do the iteration on each vts, insert it into the trie while it is already attached to the root. This way, the hash is always consistent. So delete all that code

feat: Add trie paged iteration + remove attach_to_root

---

src/cfg.rs

Generate a replicator snapshot every 8 hours (instead of 2 hours) and keep them open for 24 hours. Opening too many replicator snapshots causes too many open file handles

fix: Generate replicator snapshots every 8 hours

---

src/storage/trie/merkle_trie_tests.rs
src/storage/trie/trie_node.rs

Handle duplicates when inserting into the trie. This is an alternate implementation of the bugfix for PR #674

fix: Handle duplicates while inserting in the trie

---

src/bootstrap/replication/client_test.rs
src/bootstrap/replication/rpc_client.rs
src/bootstrap/replication/service.rs
src/network/http_server_test.rs
src/network/mod.rs

For shard-0, we insert a pre events block, which might be quite old. Syncing over p2p is quiet slow, so stream Shard-0 blocks over RPC to quickly catch up on shard-0. This takes ~5 mins to catch up (instead of ~12 hours)

feat: Do a "fast" catchup on shard-0 by streaming blocks during replication

---

src/network/http_server_test.rs
src/network/server.rs
src/network/server_tests.rs
src/proto/rpc.proto

This rpc provides us a way to know if a `LendStorage` message has been merged into snapchain.

chore: add bulk rpc for querying `LendStorage` messages
