- Cargo.toml
- src/consensus/consensus.rs
- src/core/types.rs
- src/main.rs
- src/network/gossip.rs
- src/proto/blocks.proto
- tests/consensus_test.rs
Implement basic block production
> Block production

- Cargo.toml
- src/cfg.rs
- src/connectors/mod.rs
- src/connectors/onchain_events/id_registry_abi.json
- src/connectors/onchain_events/key_registry_abi.json
- src/connectors/onchain_events/mod.rs
- src/connectors/onchain_events/storage_registry_abi.json
- src/main.rs
Read onchain events and store them in memory. 
Tested with: 
`SNAPCHAIN_ONCHAIN_EVENTS__RPC_URL=<alchemy rpc url> cargo run -- --id 1`
The on chain events consumer logs every time we receive a new onchain event. I tested further by dumping the state of the module whenever there was a new on chain event. 
Example log: 
```
2024-11-06T16:26:25.880328Z  INFO snapchain::connectors::onchain_events: Processed onchain event Event {
chain_id: 10,
block_number: 127655803,
block_hash: 0x72b93f463736aaaf79ae3ddb0583677201150fd312138620a50502fe72b69c16,
block_timestamp: 1730910383,
log_index: 86,
fid: 874469,
tx_index: 40,
version: 0,
event_type: IdRegister(
Register {
to: 0x9a6954bf025a570f987f7315a46121a7200f9770,
recovery_address: 0x00000000fcb080a4d6c39a9354da9eb9bc104cd7,
},
),
} …
```
> start consuming on chain events

- Cargo.toml
- build.rs
- src/bin/submit_message.rs
- src/network/server.rs
Add a quick submit-message script.
Instructions:
```
cargo run --bin snapchain -- --id 1
```
in another terminal:
```
cargo run --bin submit-message
```
> submit message script

- src/consensus/consensus.rs
- src/core/types.rs
- src/main.rs
- src/network/gossip.rs
- src/network/server.rs
- src/node/snapchain_node.rs
- src/proto/blocks.proto
- src/proto/rpc.proto
- tests/consensus_test.rs
Set up RPC and wiring for block sync.
> setup block sync api

- tests/consensus_test.rs
Re-add code block that was missed during a merge. Also add an assertion on message counts.
> Fix messages in tests

- src/bin/collect_stats.rs
Add stats for pending messages and max time to confirmation.
> collect more stats in script

- src/consensus/consensus.rs
- src/consensus/proposer.rs
- src/consensus/validator.rs
- src/node/snapchain_node.rs
- src/storage/store/engine.rs
- src/storage/store/mod.rs
Creates an Snapchain Engine struct that's responsible for validating and committing state changes to the db.
At a high level, I think the engine should be the only one that holds a reference to the DB, and it manages creating and committing/rolling back transactions. All the other stores should accept a transaction as a parameter and perform their db operations using that.
> Storage abstraction

- src/consensus/proposer.rs
- src/main.rs
- src/node/snapchain_node.rs
- src/storage/store/block.rs
- src/storage/store/engine.rs
- src/storage/store/mod.rs
- src/storage/store/shard.rs
- src/storage/store/utils.rs
- tests/consensus_test.rs
Initialize a db per-shard and write shard chunks separately from blocks.
> separate shard and block stores and write to shard store

- Cargo.toml
- src/bin/setup.rs
- src/consensus/consensus.rs
- src/consensus/proposer.rs
- src/node/snapchain_node.rs
Also adds the ability to:
```
cargo run --bin setup -- --propose-value-delay 2s
```
> Introduce propose_value_delay config option

- src/bin/collect_stats.rs
- src/bin/submit_message.rs
- src/consensus/proposer.rs
- src/core/message.rs
- src/core/mod.rs
- src/node/snapchain_node.rs
- src/storage/constants.rs
- src/storage/store/account/cast_store.rs
- src/storage/store/account/message.rs
- src/storage/store/account/store.rs
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/utils/cli.rs
- tests/consensus_test.rs
Support merging cast messages to store.
> Merge cast messages to store

- src/network/server.rs
Log when all rpcs are received to aid in debugging.
> add logs for all rpcs

- src/core/message.rs
- src/network/server.rs
- src/network/server_tests.rs
- src/node/snapchain_node.rs
- src/storage/store/account/link_store.rs
- src/storage/store/account/mod.rs
- src/storage/store/account/on_chain_event_store_tests.rs
- src/storage/store/account/onchain_event_store.rs
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/storage/store/mod.rs
- src/storage/store/stores.rs
- src/storage/trie/merkle_trie.rs
- src/storage/trie/merkle_trie_tests.rs
- src/utils/factory.rs
Storage unit calculations based on rent events
> Implement storage unit calculations

- src/storage/store/account/link_store.rs
- src/storage/store/account/mod.rs
- src/storage/store/account/reaction_store.rs
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/storage/store/stores.rs
- src/utils/factory.rs
Start processing reaction messages in the engine.
> port reaction store

- src/storage/constants.rs
- src/storage/store/account/message.rs
- src/storage/store/account/mod.rs
- src/storage/store/account/name_registry_events.rs
- src/storage/store/account/reaction_store.rs
- src/storage/store/account/user_data_store.rs
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/storage/store/stores.rs
- src/utils/factory.rs
Integrate user data store into the engine.
> port user data store

- src/storage/constants.rs
- src/storage/store/account/mod.rs
- src/storage/store/account/verification_store.rs
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/storage/store/stores.rs
- src/utils/factory.rs
Support verifications in the engine.
> port verification store

- src/core/message.rs
- src/storage/store/account/store.rs
- src/storage/store/account/verification_store.rs
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/storage/store/stores.rs
- src/storage/trie/merkle_trie.rs
- src/storage/trie/merkle_trie_tests.rs
- src/utils/factory.rs
Implement message pruning based on storage
> Prune messages

- src/bin/perftest.rs
- src/bin/submit_message.rs
- src/storage/store/account/store.rs
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/storage/store/stores.rs
- src/utils/cli.rs
- src/utils/factory.rs
- tests/consensus_test.rs
Revoke messages by signer when the Remove signer on chain event is merged
> Revoke messages by signer

- src/storage/store/account/onchain_event_store.rs
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/utils/factory.rs
Validate that id registration and signer exists for each user message.
> initial engine valdiations

- src/core/message.rs
- src/proto/blocks.proto
- src/storage/store/account/user_data_store.rs
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/storage/store/test_helper.rs
- src/storage/trie/merkle_trie.rs
- src/utils/factory.rs
Support for merging fname proofs and validation to ensure username can only be merged with the correct proof
> Support registering fnames as usernames

- src/network/server.rs
- src/proto/rpc.proto
This reverts commit d7a2df8ef6f9e0a1547a65bee78516590331ec6f.
> Revert "add submitLegacyMessage endpoint (#124)"

- src/network/server.rs
When the events sender gets blocked in the process of reading events out of the db, the subscribe rpc was hanging without returning the receiver. Move all the operations on the sending channel into a separate thread so that the receiver will always be returned.
> fix issue in server rpc when events sender gets blocked

- src/network/server.rs
- src/proto/rpc.proto
- src/storage/db/rocksdb.rs
- src/storage/mod.rs
This rpc is useful for understanding if messages are actually getting merged upon submit. 
```
❯ grpcurl -plaintext -proto src/proto/rpc.proto -import-path src/proto 127.0.0.1:3383 HubService/GetInfo
{
"dbStats": {
"numMessages": "23219",
"numFidRegistrations": "10",
"approxSize": "47380709"
}
}
```
> implement a get info rpc

- src/storage/store/engine.rs
Add some counters and logging for validation errors.
> add metrics and logging for validation errors

- src/network/mod.rs
- src/network/rpc_extensions.rs
- src/network/server.rs
- src/network/server_tests.rs
- src/proto/rpc.proto
- src/storage/store/account/cast_store.rs
- src/storage/store/account/link_store.rs
- src/storage/store/account/message.rs
- src/storage/store/account/reaction_store.rs
- src/storage/store/account/user_data_store.rs
- src/storage/store/engine_tests.rs
- src/storage/store/test_helper.rs
Implement read apis for most of the remaining stores
> More read apis

- src/core/mod.rs
- src/core/util.rs
- src/core/validations.rs
- src/core/validations_test.rs
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/storage/store/test_helper.rs
- src/utils/factory.rs
Add message hash validation and signature verification
> Validate message hash

- src/connectors/fname/mod.rs
- src/main.rs
Send fname transfers to the engine and include in blocks.
> include fname transfers in blocks

- .github/workflows/verify.yml
- Cargo.lock
- Cargo.toml
- Dockerfile
- Makefile
- README.md
- src/consensus/consensus.rs
- src/consensus/proposer.rs
- src/consensus/validator.rs
- src/core/types.rs
- src/main.rs
- src/network/gossip.rs
- src/node/snapchain_node.rs
- src/storage/store/engine_tests.rs
Now that Malachite has been released as a crate, we no longer need to install it via Git.
> Switch to Malachite crate

- src/connectors/fname/mod.rs
- src/connectors/onchain_events/mod.rs
- src/main.rs
- src/mempool/mempool.rs
- src/network/admin_server.rs
- src/network/server.rs
- src/network/server_tests.rs
- src/node/snapchain_node.rs
- src/storage/store/engine.rs
- src/storage/store/test_helper.rs
- tests/consensus_test.rs
Create a mempool data structure and send all messages to the mempool before routing to the engine.
> integrate Mempool data structure

- src/consensus/consensus.rs
Add a log for consensus start height so it's clear whether the db was cleared.
> add log for start height

- .github/workflows/verify.yml
- Cargo.lock
- Cargo.toml
- Dockerfile
- Makefile
- README.md
- src/consensus/consensus.rs
- src/consensus/proposer.rs
- src/consensus/validator.rs
- src/core/types.rs
- src/main.rs
- src/network/gossip.rs
- src/node/snapchain_node.rs
Consensus is breaking after the malachite upgrade. Try reverting to see if the cause is related to the upgrade.
> Revert malachite upgrade

- src/network/server.rs
Look up ens usernames in the username proof store rather than the user data store in the submit message validation.
> look up ens username in the correct store in submit message validation

- src/network/server_tests.rs
Use the API to get all casts rather than the one to get cast adds for the pagination test given we expect to see a remove.
> fix pagination test

- src/storage/db/snapshot.rs
We need a list of files in the snapshot for the download because S3 only allows us to access objects and doesn't allow us to list objects under intermediate keys.
> upload metadata for latest snapshot upload

- Cargo.lock
- Cargo.toml
- src/bin/setup_local_testnet.rs
- src/main.rs
- src/storage/db/rocksdb.rs
- src/storage/db/snapshot.rs
Download the latest snapshot from s3 on startup.
> download snapshot on startup

- Cargo.lock
- Cargo.toml
- src/bin/setup_local_testnet.rs
- src/consensus/consensus.rs
- src/consensus/malachite/host.rs
- src/consensus/malachite/mod.rs
- src/consensus/malachite/network_connector.rs
- src/consensus/malachite/snapchain_codec.rs
- src/consensus/malachite/spawn.rs
- src/consensus/proposer.rs
- src/consensus/validator.rs
- src/core/types.rs
- src/main.rs
- src/mempool/mempool_test.rs
- src/network/gossip.rs
- src/network/gossip_test.rs
- src/node/snapchain_node.rs
- src/perf/engine_only_perftest.rs
- src/proto/blocks.proto
- src/storage/store/block.rs
- src/storage/store/engine.rs
- src/storage/store/shard.rs
- src/storage/store/test_helper.rs
- tests/consensus_test.rs
Integrate with malachite sync so nodes can automatically fetch and replay blocks from peers
> Integrate malachite sync

- src/connectors/fname/mod.rs
- src/connectors/onchain_events/mod.rs
- src/main.rs
- src/proto/node_state.proto
- src/storage/store/node_local_state.rs
Start ingesting fname transfer from where the node stopped before restart.
> pick up fname transfer ingest from where it left off

- src/network/server.rs
- src/network/server_tests.rs
- src/proto/request_response.proto
Add shard info to  getInfo so we have more visibility into the current heights.
> Add shard info to getInfo RPC

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cliff.toml
Start using git cliff for generating changelogs and release v0.1.1
> chore: Release v0.1.1

- src/connectors/fname/mod.rs
- src/connectors/onchain_events/mod.rs
- src/main.rs
- src/mempool/mempool.rs
Add metrics for onchain events and fname ingest. Also lumped in a couple small fixes in these areas + communication with mempool.
> observability and fixes for ingest to mempool communication

- README.md
- docker-compose.read.yml
- src/consensus/proposer.rs
- src/main.rs
- src/network/http_server.rs
- src/network/server.rs
- src/proto/request_response.proto
- src/storage/db/rocksdb.rs
- src/storage/store/block.rs
- src/storage/store/shard.rs
- tests/consensus_test.rs
Add documentation for how to run a read node and related small fixes around logging and add missing Info http endpoint
> feat: Read node documentation and related fixes

- Cargo.lock
- README.md
- docker-compose.read.yml
Fix read node config and update readme
> fix: Fix read node config

- src/consensus/malachite/host.rs
- src/consensus/malachite/spawn.rs
- src/consensus/validator.rs
- src/node/snapchain_node.rs
- src/storage/store/engine.rs
- src/utils/statsd_wrapper.rs
Add more timing metrics to get visibility into block production performance
> perf: Add more perf metrics

- src/consensus/consensus.rs
- src/consensus/malachite/spawn.rs
- src/consensus/proposer.rs
> perf: Tune consensus timeouts

- src/consensus/malachite/host.rs
- src/consensus/proposer.rs
Host actor sometimes crashes if we don't have the proposed value. This can happen sometimes on restart and malachite replaces from WAL. In these cases, try restarting the height to force malachite to fall back to sync to recover.
> fix: Fix host crash by restarting height if proposed value not found

- docker-compose.read.yml
Change the config for the read node docker-compose to enable snapshot download.
> enable snapshots for read nodes

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> chore: Release 0.1.4

- Cargo.lock
- Cargo.toml
- src/bin/dump_wal.rs
This PR adds a very basic CLI for dumping the contents of the WAL to the console.
```
$ cargo run -- bind dump_wal /path/to/wal/file
```
```
WAL Dump
- Entries: 36
- Size:    3884 bytes
Entries:
- #0: Timeout(Timeout { kind: Propose, round: Some(0) })
- #1: ConsensusMsg(Vote(SignedMessage { message: Vote { vote_type: Prevote, height: Height { shard_index: 0, block_number: 662592 }, round: Some(0), shard_hash: Nil, voter: Address(b5a20adf31d58c6480cc46e6c1cba5e13396228a465a7f9fd34d2bb665cc68a5) }, signature: Signature([10, 106, 56, 173, 50, 214, 78, 41, 110, 19, 246, 41, 111, 241, 31, 3, 206, 47, 238, 118, 209, 232, 51, 35, 96, 167, 165, 136, 84, 234, 251, 117, 247, 200, 42, 220, 35, 110, 175, 65, 206, 200, 196, 221, 236, 161, 52, 222, 140, 0, 232, 248, 205, 204, 104, 20, 45, 166, 224, …
```
> chore: Add `dump_wal` utility

- docker-compose.read.yml
This reverts commit 97495feb5cbff2a8646f980267c0dcfab6f00362.
> Revert "enable snapshots for read nodes (#301)"

- src/storage/constants.rs
- src/storage/store/block.rs
- src/storage/store/shard.rs
So we can look up blocks by timestamp.
Needs tests. Will add separately.
> feat: Add a timestamp index for block heights

- src/connectors/fname/mod.rs
Add logs to figure out when fname transfers are getting picked up.
> chore: add more logs for fname transfers

- Cargo.lock
- src/perf/trie_only_perftest.rs
- src/storage/store/account/cast_store.rs
- src/storage/store/account/link_store.rs
- src/storage/store/account/message.rs
- src/storage/store/account/name_registry_events.rs
- src/storage/store/account/onchain_event_store.rs
- src/storage/store/account/reaction_store.rs
- src/storage/store/account/store.rs
- src/storage/store/account/user_data_store.rs
- src/storage/store/account/username_proof_store.rs
- src/storage/store/account/verification_store.rs
- src/storage/store/block.rs
- src/storage/store/engine.rs
- src/storage/trie/commit_rollback_tests.rs
- src/storage/trie/merkle_trie.rs
- src/storage/trie/merkle_trie_tests.rs
- src/storage/trie/trie_node.rs
- src/storage/trie/util.rs
Added low level optimizations to squeeze more performance out of snapchain
> chore: perf improvements

- src/consensus/proposer.rs
- src/core/validations/error.rs
- src/core/validations/message.rs
- src/core/validations/message_test.rs
- src/main.rs
- src/network/server.rs
- src/network/server_tests.rs
- src/node/snapchain_node.rs
- src/node/snapchain_read_node.rs
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/storage/store/test_helper.rs
- tests/consensus_test.rs
Fix some missing network validations
> feat: Validate for message network

- CHANGELOG.md
- src/main.rs
- src/mempool/mempool.rs
- src/network/gossip.rs
> fix: Higher channel sizes, and remove read node expiry

- src/consensus/proposer.rs
- tests/consensus_test.rs
> feat: add genesis block message

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- docker-compose.mainnet.yml
> chore: Release 0.2 (mainnet)

- Cargo.lock
- src/connectors/fname/mod.rs
- src/connectors/onchain_events/mod.rs
- src/consensus/consensus.rs
- src/main.rs
- src/mempool/mempool.rs
- src/mempool/mempool_test.rs
- src/network/admin_server.rs
- src/network/gossip.rs
- src/network/gossip_test.rs
- src/network/http_server.rs
- src/network/server.rs
- src/network/server_tests.rs
- src/perf/engine_only_perftest.rs
- src/proto/request_response.proto
- src/storage/store/test_helper.rs
- tests/consensus_test.rs
Return the size of the mempool in getInfo
> feat: Add mempool size to getInfo

- src/network/gossip.rs
Reconnect to bootstrap peers if connection is lost
> fix: Auto reconnect to bootstrap peers if connection is lost

- docker-compose.testnet.yml
> chore: add testnet configs

- src/cfg.rs
- src/jobs/block_pruning.rs
- src/jobs/event_pruning.rs
- src/jobs/mod.rs
- src/lib.rs
- src/main.rs
- src/network/server.rs
- src/network/server_tests.rs
- src/storage/store/account/event.rs
- src/storage/store/engine.rs
- src/storage/store/mod.rs
- src/storage/store/shard.rs
- src/storage/store/stores.rs
- src/storage/store/stores_test.rs
- src/utils/factory.rs
Background job to delete events after 3 days (same as hubs)
> feat: Add a background job to prune events

- Cargo.lock
- Cargo.toml
- src/mempool/mempool.rs
- src/mempool/mempool_test.rs
- src/mempool/mod.rs
- src/mempool/rate_limits_test.rs
Add rate limits in the mempool.
> feat: rate limits in mempool

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/mempool/mempool.rs
- src/mempool/mempool_test.rs
- src/mempool/mod.rs
- src/mempool/rate_limits_test.rs
- src/network/server.rs
- src/network/server_tests.rs
- tests/consensus_test.rs
Enable submitting messages to read nodes now that backfill is done.
> chore: enable submit to read nodes

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> chore: Release 0.2.3

- Cargo.lock
- Cargo.toml
- src/jobs/mod.rs
- src/jobs/snapshot_upload.rs
- src/main.rs
- src/network/admin_server.rs
- src/storage/db/snapshot.rs
Add an automated snapshot upload job. 
Note: I needed to update dependency versions to fix the build.
> feat: add snapshot upload background job

- src/network/server.rs
We currently only count a single type of failure and we don't record submit message timings on failures.
> fix: properly track stats on submit message failures

- src/network/http_server.rs
If this works as expected it'll be necesary to look over the hubble spec and the snapchain spec and alias any divergence.
Addresses #357
> fix: change query params to be backwards compatible with hubs

- src/network/http_server.rs
Closes https://github.com/farcasterxyz/snapchain/issues/406
> refactor: change expected return types for `SignerEventBody`

- src/consensus/malachite/spawn_read_node.rs
Reduce read node sync timeout to 1s.
> fix: reduce read node sync timeout

- src/consensus/malachite/network_connector.rs
Add logging to track sync requests
> chore: add logging for sync

- build.rs
- src/network/http_server.rs
- src/network/server.rs
- src/network/server_tests.rs
- src/proto/request_response.proto
- src/proto/rpc.proto
Inheriting from https://github.com/farcasterxyz/snapchain/pull/411. 
Merged main and cleaned up some api inconsistencies
> fix: implement /v1/events HTTP API endpoint

- src/connectors/fname/mod.rs
- src/connectors/onchain_events/mod.rs
- src/core/error.rs
- src/mempool/mempool.rs
- src/mempool/mempool_test.rs
- src/network/gossip.rs
- src/network/gossip_test.rs
- src/network/server.rs
- src/perf/engine_only_perftest.rs
- src/storage/store/account/store.rs
- tests/consensus_test.rs
Inheriting from https://github.com/farcasterxyz/snapchain/pull/452
Fixes https://github.com/farcasterxyz/snapchain/issues/384
> feat: Forward errors from mempool to client

- src/core/message.rs
- src/network/server.rs
- src/network/server_tests.rs
- src/proto/hub_event.proto
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/storage/store/stores.rs
- src/storage/store/test_helper.rs
- src/utils/factory.rs
This makes it much easier to determine how far behind you are. 
https://github.com/farcasterxyz/snapchain/issues/397
> feat: add timestamp to hub event

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> chore: release v0.2.14

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> chore: release v0.2.15

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> chore: release v0.2.16

- src/network/http_server.rs
Closes https://github.com/farcasterxyz/snapchain/issues/417
> feat: implement eventById in the http server

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> chore: release v0.2.17

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> chore: release v0.2.18

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> chore: release v0.2.19

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> chore: release v0.2.20

- src/storage/db/snapshot.rs
This should make the snapshot uploads more robust
> fix: Log s3 errors better and retry on upload

- docker-compose.mainnet.yml
Automatically restart production snapchain nodes if they go down
> always restart automatically

- src/storage/db/snapshot.rs
Fix for https://github.com/farcasterxyz/snapchain/issues/379
> fix: Retry when snapshot download fails

- src/consensus/malachite/read_node_actors_test.rs
- src/consensus/read_validator_test.rs
- src/core/validations/validations_test.rs
- src/core/validations/verification.rs
- src/main.rs
- src/mempool/mempool.rs
- src/mempool/mempool_test.rs
- src/mempool/rate_limits_test.rs
- src/network/server_tests.rs
- src/perf/engine_only_perftest.rs
- src/storage/store/account/name_registry_events.rs
- src/storage/store/account/user_data_store.rs
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/storage/store/test_helper.rs
- src/utils/factory.rs
- src/version/version.rs
- tests/consensus_test.rs
Updated https://github.com/farcasterxyz/snapchain/pull/442 to feature flag this since it's a protocol breaking change.
Fixes https://github.com/farcasterxyz/snapchain/issues/438
> fix: Handle fname transfers across shards

- src/cfg.rs
- src/connectors/onchain_events/mod.rs
- src/main.rs
- src/storage/store/node_local_state.rs
Make the tier registry contract address configurable so we can test with a test contract.
> chore: make tier registry contract address configurable for testing

- tests/consensus_test.rs
- Adds some basic assertions to tests to ensure sync / consensus is working
- Fixes port assignment issue so tests can be run concurrently
- Introduces some higher-level helper methods and assertions for writing tests
> Refactor and update consensus tests

- src/connectors/onchain_events/mod.rs
Add the relevant chain as a tag to onchain events logs. This will help us distinguish between issues with base vs op rpc subscriptions.
> chore: add chain as a tag to onchain events logs

- tests/consensus_test.rs
Previously we waited for one node to have reached the conditional; instead we should wait for all nodes to pass.
> Evaluate predicate on all nodes in consensus test wait funcs

- src/network/rpc_extensions.rs
- src/network/server_tests.rs
Fixes https://github.com/farcasterxyz/snapchain/issues/501
> fix: Handle empty page tokens

- Cargo.lock
- Cargo.toml
- src/core/validations/validations_test.rs
- src/core/validations/verification.rs
- src/network/server.rs
- src/node/snapchain_node.rs
- src/node/snapchain_read_node.rs
- src/storage/store/engine.rs
- src/storage/store/engine_tests.rs
- src/storage/store/test_helper.rs
- src/utils/factory.rs
> fix: restore fname tests using custom signer

- src/network/server_tests.rs
- src/storage/store/account/cast_store.rs
- src/storage/store/engine_tests.rs
- src/storage/store/test_helper.rs
- src/utils/factory.rs
Fixes https://github.com/farcasterxyz/snapchain/issues/554
We weren't passing the correct last key back to the client
> fix: Fix pagination bug for certain api endpoints

- src/mempool/rate_limits_test.rs
- src/network/http_server.rs
- src/network/server_tests.rs
- src/perf/engine_only_perftest.rs
- src/proto/request_response.proto
- src/storage/store/account/on_chain_event_store_tests.rs
- src/storage/store/account/onchain_event_store.rs
- src/storage/store/engine_tests.rs
- src/storage/store/stores.rs
- src/storage/store/stores_test.rs
- src/storage/store/test_helper.rs
- src/utils/factory.rs
Implements the Storage Re-denomination FIP: https://github.com/farcasterxyz/protocol/discussions/229
As part of it, we're also extending the expiry of storage units that are set to expire on Aug 29 2025 by one year.
> feat: Storage redenomination

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> chore: Release 0.4.0

- README.md
- docker-compose.mainnet.yml
- scripts/snapchain-bootstrap.sh
- scripts/snapchain.sh
- site/docs/pages/getting-started.mdx
- site/docs/pages/guides/running-a-node.mdx
Fixes https://github.com/farcasterxyz/snapchain/issues/444
> feat: Port install and autoupgrade script from hubble

- src/proto/replication.proto
- src/replication/error.rs
- src/replication/replication_engine_tests.rs
- src/replication/replication_server.rs
- src/replication/replication_stores.rs
- src/replication/replicator.rs
- src/storage/store/account/onchain_event_store.rs
Adds endpoints for fetching replication shapshot metadata and transactions for a given shard.
> Add transaction replication endpoint(s)

- src/connectors/onchain_events/mod.rs
We're not picking up Base Pro events for reasons that are not fully clear. Switch to getLogs to workaround it.
Tested locally.
> fix: Switch to polling getLogs for Base pro events to fix not picking up events

- .gitignore
- src/core/validations/cast_test.rs
Add extra logging to failing test so we can catch what is failing
> misc: Log flaky test failure

- src/storage/store/migrations/mod.rs
1. Don't log migration version checks too many times
2. Don't allow multiple migrations to run at once. - This is needed because we construct the ShardEngine in many places, and we might accidentally trigger multiple parallel migrations. While it might OK to run them parallelly, we don't want to stress the DB too much.
> fix: Don't run parallel migrations + quiet migration logs

- src/storage/db/rocksdb.rs
Allow RocksDB to be opened in a new bulk write optimized mode for replication
> feat: Create a new bulk-optimized DB option

- src/core/validations/error.rs
- src/core/validations/message.rs
- src/core/validations/message_test.rs
- src/proto/message.proto
- src/version/version.rs
Implement https://github.com/farcasterxyz/protocol/discussions/247. 
Will go live on the protocol on Sep 24 (engine version 10)
> feat: Add profile token user data type

- src/bootstrap/replication/service.rs
Minor fix so that ETA is shown properly (A day has 24hrs, not 8 :) )
> fix: Update ETA constant for replication

- src/version/version.rs
Pull the protocol release date in by a week.
> chore: set protocol release date to 10/8
